### ISSUE TITLE
Enhancement: ability to set image classes

### ISSUE THREAD

**Issue by nick-denry** [dev7ch/luya-ext-slick#15]
Hi!

Is it possible to add a filed for image class attribute? Slick slider images needs extra classes sometimes.
If yes, I could do a PR.

**Comment by dev7ch** [comment]
Hey @nick-denry,

yes, sure the extension can be enhanced with a new field for a css class.

It would be great if you can make a PR :)

**Comment by dev7ch** [comment]
@nick-denry are u still on it?

**Comment by dev7ch** [comment]
close due more than 3 months of inactivity, plz reopen if required, thx.
