### ISSUE TITLE
Can't get block config option works

### ISSUE THREAD

**Issue by nick-denry** [dev7ch/luya-ext-slick#17]
Hi!

I've try to put slick config as a string or as filename into block config option, but bot not working for me

Is it possible to set this config for slick block?

```js
{
  infinite: true,
  slidesToShow: 3,
  slidesToScroll: 3
}
```

![2018-05-30 01 50 04](https://user-images.githubusercontent.com/1450983/40689721-281ec040-63ac-11e8-8325-c9f2a8c424b1.png)

**Comment by dev7ch** [comment]
Hi @nick-denry ,
currently, this option isn´t fully implemented yet, as you can see here

https://github.com/dev7ch/luya-ext-slick/blob/master/src/blocks/SlickBlock.php#L76

**Comment by dev7ch** [comment]
For now the slick config works only if the widget is implemented directly in views.

Then you could set the options directly in the widget or load a file, e.g.:

```php
<?= SlickWidget::widget([
    'images'            => $images,
    'slickConfigFile' => 'path/to/yourConfig.php'  // or a .json file
]);
?>
```

for more see: https://github.com/dev7ch/luya-ext-slick/blob/master/src/SlickWidget.php#L20

**Comment by nick-denry** [comment]
Thanks. I'll create new issue after some checks.
